Updating dependencies
vazco/meteor-universe-i18n pull request #167
Opened 2022-10-18 17:00 UTC by zendranm

This PR updates the following dependencies:
- typescript to v4.8.4
- eslint-config-vazco to 7.0.0

2022-10-18 18:09 UTC, radekmie approved these changes

2022-10-18 18:09 UTC, radekmie commented on package.json
> +    "typescript": "^4.8.4"
Let's use pinned versions.

2022-10-18 18:23 UTC, radekmie approved these changes

2022-11-18 13:39 UTC, radekmie reviewed
Both `lint:js` and `lint:ts` now work.

2022-11-18 13:39 UTC, radekmie commented on tsconfig.json
> +  "include": ["source/**.*"],
I think it's enough to say `"source"`.

2022-11-18 13:39 UTC, radekmie commented on package.json
> +    "lint:ts": "tsc --noEmit source/common.ts",
1. Why only `source` get's linted?
2. Why only `source/common.ts` get's `tsc`ed?

2022-11-18 14:13 UTC, radekmie requested changes

2022-11-18 14:13 UTC, radekmie commented on source/server.ts
> +import { current } from 'fibers';
This is not correct, as `current` get's overridden in the runtime, therefore we have to access it every time.

2022-11-18 14:52 UTC, piotrpospiech approved these changes

2022-11-18 14:53 UTC, merged